apiVersion: v1
kind: Service
metadata:
  name: youdovezu-app
  namespace: youdovezu
spec:
  selector:
    app: youdovezu-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP

